### ISSUE TITLE
Old version deactivated, new version doesn't work

### ISSUE THREAD

**Issue by vladtheimpalerSr** [pFindStudio/pLink2#14]
As was the peculiar custom with pLink creators, the old version expired in the new year. The new, pLink2, isn't able to process the files the old one was processing just fine. My predicament is that I have a ton of new spectra to process, including those generated for our collaborators, who rely on our X-link discovery work. Very irresponsible practice.

**Comment by 01joy** [comment]
Hi vladtheimpalerSr,

I'm sorry that pLink2 didn't work with you.

From your last post #12 , it seems there is some problem with the mgf file, could you provide me with the fasta and mgf file through email, so that I can reproduce the issue.

As for the pLink1, please contact plink@ict.ac.cn for details.

Thanks for your patience with pLink2.
