### ISSUE TITLE
different enzyme 

### ISSUE THREAD

**Issue by sulezinha** [pFindStudio/pLink2#16]
Hi,
I performed pLink2 searches with the default enzyme of Trypsin. Then, I only changed Trypsin to Trypsin_P and performed another pLink2 search. However, I got the same results. 
I was expecting some changes in the results because I changed the enzyme, is there a bug related to changing the enzyme? 
Best,
Şule

**Comment by daheitu** [comment]
The difference between Trypsin and Trypsin_P is that Trypsin_P just ignore the K/R after P when generating the search database(peptides), because the default "miss cleavage site" is 3, pLink2 will consider almost peptides in Trypsin_P digestion database when enzyme was set to "Trypsin", so I think the results will be a little different.

**Comment by 01joy** [comment]
Hi @sulezinha ,

@daheitu is right. The correct configuration should be like this:

![image](https://user-images.githubusercontent.com/8603895/35467593-7daf9dc0-034b-11e8-8007-134e03ae7200.png)

We have mistaken the configuration of Trypsin_P, which ignores the K/R followed by P. Attached is the correct enzyme configuration file, rename it as enzyme.ini and replace the old enzyme.ini in pLink2/bin folder.

[enzyme.txt](https://github.com/pFindStudio/pLink2/files/1669696/enzyme.txt)

**Comment by 01joy** [comment]
Hi @sulezinha ,

This bug has been solved in pLink 2.3.0, which is released on January 31, 2018, please goto http://pfind.ict.ac.cn/software/pLink/index.html#Downloads to download the new version and try again.

Thanks for your feedback.

**Comment by sulezinha** [comment]
super, thank you @01joy
