### ISSUE TITLE
missed cleavage & peak picking

### ISSUE THREAD

**Issue by IwanParf** [pFindStudio/pLink2#18]
Dear developers,
default setting for missed cleavages is 3. Does that include the lysine which reacted with a xlinker (i.e. 1 MC caused by the xlinker and 2 MC from actual trypsin missed cleavage), or does that go without saying (i.e. in certain cases a peptide with 3 MC plus the lysine that reacted with the xlinker)?

2nd question:
in plink 1 it was possible to specify ppm windows around isotopes to correct for wrong monoisotopic mass picking during acquisition. In plink2 there is no such option. What is the default and is it possible to change it? Default in plink 1 were 5 windows from 0 to +4, which was overlapping with a d4-labelled xlinker in a quantitation experiment for instance. 

By the way, is there going to be a publication explaining all such features of plink2 soon?

Best,

Iwan

**Comment by 01joy** [comment]
Hi @IwanParf ,

The missed cleavages do include xlinker site, because pLink2 first generates all digested peptides not considering the linker sites, then recombine them into a pair. This procedure might be a little different from the real wet experiment, in which cross-linking is ahead of digestion. If you take the linked site not a missed cleavage, and want to set 3 missed cleavages, you should choose 4 in pLink2.

As for the second question. Once loaded with RAW files, pLink2 will call pParse to automatically extract and calibrate multiple precursor ions for each tandem mass spectrum. So, pParse plays the role of multiple ppm windows around isotopes, and does better. That's why I always suggest you run pLink2 directly with RAW files rather than MGF files extracted by other tools.

For more about pParse, please see http://pfind.ict.ac.cn/software/pParse/index.html.

**Comment by IwanParf** [comment]
thank you for your speedy response! I am looking forward to the publication.
