### ISSUE TITLE
Difference between SS_0 and SS Linker

### ISSUE THREAD

**Issue by armadillocommander** [pFindStudio/pLink2#26]
Hi,

In pLink 2.3.2, there's two linker options available: SS_0 and SS for disulfide bond linked peptide identification. SS only has NEM (C) as a variable modification and SS_0 only has -H (C) as a fixed modification (I guess it means in the MS2 spectra the disulfide bond linked peptide will generate a R-S fragment). So for the purpose of disulfide bond mapping, what's the difference of these two linkers? 

Thanks!

**Comment by yxfkq** [comment]
Hi armadillocommander,

These two linker options are both for the purpose of disulfide bond mapping.  

SS option can allow the identification at most one disulfide bond and set a variable modification NEM (C) as default because the modification is common to our knowledge. You can also remove it from the list. 

SS_0 option is an advanced option. It set a fixed modification of −1.007285 Da on cysteine and the disulfide mass was set to 0 to allow the identification of more than one disulfide bond in a peptide pair. However, this option can only report the sites which are linked when pLink finding more than one disulfide bonds and doesn't report disulfide bonds between two explicit sites because MS2 information can hardly help us determine the reliable disulfide bond mapping results.

R-S fragments have been considered in our scoring algorithm but have nothing to do with the two options.

All in all, these two options have different identification targets. SS option is apt to identify only one disulfide bond and SS_0 option is apt to identify more than one disulfide bond. In other words, one option complements the other one. You can try both of them to find more disulfide bonds.

**Comment by armadillocommander** [comment]
Thank you so much for the explanation in detail! This is greatly helpful!
