### ISSUE TITLE
Understanding the Output/Graphs and dealing with impurities

### ISSUE THREAD

**Issue by mgold2** [pFindStudio/pLink2#32]
I have quite a few questions about the output as well as the software analysis itself. Any help would be much appreciated. 
The first thing I was wondering is what the "precursor error distribution" graph is for. 

![image](https://user-images.githubusercontent.com/40864982/42476421-28c36d94-838b-11e8-9d3d-d0a2221d29a3.png)

also the "Histogram of filtered precursors"

![image](https://user-images.githubusercontent.com/40864982/42476472-4fdd2fb4-838b-11e8-9576-d76019464bb6.png)

Another issue I ran into with the results is the score. When reviewing the cross-linked peptides, I plotted the matches to a 3D model and found that they were too far apart for it to be a successful cross-link with the BS(PEG)5 cross-link we are using. The score for these were in the range of 0.1-0.2. What is a score that would be more indicative to a success?

The last question i have involves impurities. If a spectra has impurities plotted on it, would the spectra be thrown out by the software? I might have a polymer impurity in my sample, but I should still have quite a bit of protein/peptides. pLink2 was only able to find a few peptides total. 
![image](https://user-images.githubusercontent.com/40864982/42476818-5a78a952-838c-11e8-8013-925a44534b1c.png)
Is there any way to filter out the "noise" on the spectrum from the polymer? Does the program get stuck when this happens? 
I plan on making a new sample and filtering it with some C18 ZIP-Tips, has that been successful for anyone else? 

I know this is a lot to resolve in one issue, but I feel that my results might make more sense while trying to solve all of these together. Thank you

**Comment by mgold2** [comment]
Also, how is the Score determined?

**Comment by armadillocommander** [comment]
Your precursor mass error distribution is a little bit weird. In theory it should be close to Gaussian distribution (especially for the filtered precursor ions, your mu and sigma values look quite high), but yours are more like evenly distributed across the whole mass error window. What type of instrument did you use for the data acquisition?
![all_precursor_error_dist](https://user-images.githubusercontent.com/35280275/42478273-f741678c-8388-11e8-81c0-006cd4e3b493.png)
![filtered_precursor_error_dist](https://user-images.githubusercontent.com/35280275/42478276-fb735c02-8388-11e8-8aba-d9c15fde8b34.png)


Also, the number of the matched spectra/cross-linked peptides pairs are also quite low, on average there was only one spectrum was matched for each precursor, based on my experience this type of one-hit wonders are more likely caused by some random matches. Can you use the pLabel to check the quality of those matched spectra?

For your last question, I suggested you read some paper to understand how shotgun proteomics work. To identify the peptides, the MS2 spectrum of a precursor ion was matched to the fragments predicted from the protein sequence database: more fragment ions matched, higher confidence in identification. So it doesn't matter if you have the spectra belonging to the "impurities", they will just remain unidentified and filtered out by the software. Unless you have some impurities in your sample that can repress the MS signal of the peptides (for example, salt, TFA, detergent), otherwise likely it won't interfere the peptide identification.

**Comment by mgold2** [comment]
We used an Orbitrap LC-MS. Our control was tagged with dimethyl groups(control that has no crosslink) and the cross-linked proteins were tagged with deuterated dimethyl (has BS(PEG)5 crosslinker) on the N-term. 
Thanks for explaining the Score.

**Comment by 01joy** [comment]
Thank you @armadillocommander for giving a quite good explanation.

Just some additional comments:

1. The "precursor error distribution" plots the precursor errors of all top-1 PSMs without FDR filter, including regular, mono-linked, loop-linked, and cross-linked PSMs. T means target-target, U means target-decoy, and D means decoy-decoy. Thus, a typical precursor error distribution should be like what @armadillocommander has posted, where the blue dots (T) gather around +/-0ppm, and have higher scores, resulting in a Gaussian distribution. Whereas, the red dots (D) usually evenly distribute across the ground, as they are random matches having lower scores.

2. The "Histogram of filtered precursors" is very similar with the "precursor error distribution" except that it only plots the PSMs passing the FDR threshold. Additionally, the mean (mu) and variance (sigma) of filtered precursor error distribution are given. They can be regarded as the system deviation of your instrument. Similarly, a typical histogram of filtered precursors should be like what @armadillocommander has posted, where a smooth Gaussian distribution is plotted and the mean (mu) is around +/- 0ppm. Otherwise, the instrument has to be calibrated.

3. The numbers of the matched spectra/cross-linked peptides pairs are quite low. What's more, the numbers of the matched **regular** spectra/peptides are quite low too. A typical result of a cross-linked sample should be like this below, where the number of matched regular spectra is usually the most, and then the matched cross-linked spectra. As @armadillocommander said, your numbers are quite low, wondering if they are one-hit wonders. You can use the pLabel to check the quality of those matched spectra.
![qq 20180710101723](https://user-images.githubusercontent.com/8603895/42486360-5afa63c8-842e-11e8-87f1-b4cf3a33f190.png)

4. For the score, please see this issue: https://github.com/pFindStudio/pLink2/issues/10. The smaller the score, the more confident the PSM. A good PSM usually has score like 1e-3 ~ 1e-6, I also see some as good as 1e-10.

Thanks for using pLink2.

**Comment by mgold2** [comment]
Great responses. Thank you.
