### ISSUE TITLE
Wiff file support and MGF file processing

### ISSUE THREAD

**Issue by zrpeak** [pFindStudio/pLink2#38]
Hi, I wonder if there is a plan for supporting the processing of SCIEX wiff files in pLink. Now I need to run pParse solely to transform the wiff files into pf2 files, and then use the pf2 files for input. I think it will be more convenient if the wiff transform feature is integrated into pLink, just as that in pFind3. And it will be help if there could be a guide or explanation for the parameters in Data Extration (e.g. Precursor score).

By the way, I have problems when processing the MGF files with pLink (and that's why I have to use pf2 files for input). It seemed that the software cannot load the spectra in MGF files, no matter that converted by pParse or msConvert in ProteoWizard. Is there any parameters need to be set when transform other format to MGF?

Many Thanks,
Peak

**Comment by 01joy** [comment]
Hi @zrpeak ,

The current version of pLink2 doesn't support wiff data, and manually converting to pf2 by pParse is a compromised way. We will consider to support wiff data like pFind3 in the future.

As for MGF file, pLink2 supports MGF file, at least MGF file extracted by pParse. Additionally, pLink2 supports MGF file extracted by PD since [version 2.3.0](http://pfind.ict.ac.cn/software/pLink/release_notes.html#v2.3.0).

As MGF files converted by different software may have different formats, we recommend you to use pParse.

If it's possible, please send me your wiff file, MGF file, fasta file, and parameter file, so that I can debug them for you.

Thanks for your feedbacks.

**Comment by zrpeak** [comment]
@01joy Thank you for your help.

I tried again with the MGF file that generated by pParse and found that it actually can work. Sorry for the mistake. It just needs longer time to calculate the number of spectra and I mistake it for unable to load them.

MGF files generated from msConvert stuck for hours, so I think it is not compatible. 

The MGF format generated by pParse is:
BEGIN IONS
TITLE=Name.14.14.2.0.dta
CHARGE=2+
RTINSECONDS=0.0838330
PEPMASS=352.890000
114.521070 1.0
115.934480 1.0
......
END IONS
BEGIN IONS
TITLE=Name.17.17.2.0.dta
CHARGE=2+
RTINSECONDS=0.1128330
PEPMASS=448.880000
179.935300 6.0
212.927520 3.0
......

While for MGF format generated by msConvert is:
BEGIN IONS
TITLE=Name.14.14. File:"Name.wiff", NativeID:"sample=1 period=1 cycle=13 experiment=2"
RTINSECONDS=5.03
PEPMASS=352.893869571091
118.942389 6.0
150.9445502 9.0
......
END IONS
BEGIN IONS
TITLE=Name.17.17. File:"Name.wiff", NativeID:"sample=1 period=1 cycle=15 experiment=2"
RTINSECONDS=6.77
PEPMASS=448.879363180174
223.9410627 3.0
230.8596145 3.0
......

It seems that the information of ion charge is missing in the MGF format generated by msConvert. And this may be the reason why there's error in processing...

By the way do you have any idea about the parameters of pParse? Comparing to its default parameters, pLink set -a (check_activationcenter) to 0 and results more precursor ions. And -t (mars_threhold) is -0.5, different from -0.34 in pFind. I wonder how to adjust them to get a balance between searching speed and hit number.

**Comment by 01joy** [comment]
Hi @zrpeak ,

Yes, for MGF file, due to its variable formats, pLink2 will check its validity before seraching, resulting in a long time to load. pf2 is our own format about MS2 spectra, it's highly structured and is not likely to have wrong format, so it is more efficient to proceed. pf2 is more recommended for searching.

In the next version, we will add a warning when charge information is missing in MGF file instead of just crash. Thanks for your feedback.

As for pParse parameters, pLink set -a to 0 to obtain more precursor ion candidates. I have checked that both pLink2 and pFind3 set -t as -0.5. We have optimized these pParse parameters, I think the default parameters are good. Generally spearking, the lower the mars_threshold (-t), the more the precursor ion candidates, but also the longer the search time.
