### ISSUE TITLE
pLink2 crash after start search

### ISSUE THREAD

**Issue by victordavid1** [pFindStudio/pLink2#51]
I am trying to find dissulfide bonds by pLink2. I load my MGF file and setup all parameters. When I try to search, pLink2 close. Can anyone help me?

**Comment by 01joy** [comment]
Dear @victordavid1 ,

Could you tell me in which stage did pLink2 crash, at the beginning of the search or when generating reports?

Moreover, we suggest that you load RAW files directly instead of MGF files, as some MGF formats may not compatible with pLink2. If you could send me the MGF file, I will check it for you.

**Comment by victordavid1** [comment]
Thank you for the reply. I could resolve the problem. Apparently, put all the files on the C: resolve the problem.
