### ISSUE TITLE
Amino acid U setting for plabel

### ISSUE THREAD

**Issue by yangbinglpp** [pFindStudio/pLink2#7]
Hi pFinder,

I have installed pLink2 today and set "R21=U|C(9)H(8)N(1)O(4)S(1)|" in pLink.ini file. When I use plabel to label my spectrum. Weight of Amino acid U was still count as 0. Could you please help me to check this issue?

Best
Bing

**Comment by yxfkq** [comment]
Hi yangbinglpp,

Thanks for using pLink.

I am sorry to tell you that the software pLabel integrated in pLink2 has not supported user-defined amino acids so far.

An alternative solution is given below:
1 download a standalone version of pLabel from [http://pfind.ict.ac.cn/software/pLabel/index.html](url)
2 calculate the mass of user-defined amino acids instead of elemental composition
3 change aa.ini file to set new amino acids in the standalone version of pLabel
4 use the standalone version of pLabel to label your spectrum with user-defined amino acids

FYI, the format of file aa.ini which supports user-defined amino acids is shown below:
(The format is the same in pLink1. If you have ever used pLink1, it should be easy for you.)

![image](https://user-images.githubusercontent.com/14831347/34598983-00dd693e-f22b-11e7-8947-3ac9e19fb810.png)

-------------
Best regards,
The pLink Team of pFind Lab
Institute of Computing Technology
Chinese Academy of Sciences
plink@ict.ac.cn
http://pfind.ict.ac.cn
